# Generated by Django 3.1.1 on 2020-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default='', max_length=8)),
                ('twitterhandle', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
