# Generated by Django 3.1.1 on 2020-09-29 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default='')),
                ('twitterhandle', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField(default='')),
                ('tweet', models.CharField(default='', max_length=280)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostReactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactionsid', models.IntegerField(default='')),
                ('postlikes', models.IntegerField(default='')),
                ('postcomments', models.CharField(default='', max_length=280)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcapi.posts')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentsid', models.IntegerField(default='')),
                ('postcomments', models.CharField(default='', max_length=280)),
                ('reactionsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcapi.postreactions')),
            ],
        ),
    ]
