# Generated by Django 3.1.1 on 2020-10-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcapi', '0003_auto_20200928_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreactions',
            old_name='postcomments',
            new_name='reactioncomments',
        ),
    ]
