# Generated by Django 3.1.3 on 2020-11-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcapi', '0004_auto_20201030_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitterhandle',
            new_name='username',
        ),
    ]
