# Generated by Django 3.1.3 on 2020-11-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcapi', '0005_auto_20201114_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default='')),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='twitterhandle',
        ),
        migrations.AlterField(
            model_name='posts',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcapi.auth_user'),
        ),
    ]
