# Generated by Django 3.1.3 on 2020-11-14 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcapi', '0006_auto_20201114_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='twitterhandle',
            new_name='username',
        ),
    ]
