# Generated by Django 3.1.3 on 2020-11-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcapi', '0008_auto_20201114_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
