name: Build API Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:   
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: docker build
      run: |
        docker build . --file Dockerfile --tag clone-api:$(date +%s)
        pytest
